apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: git-resolver-test
spec: 
  params: 
    - default: ""
      description: the url to clone
      name: git-url
      type: string 
    - default: "default message"
      description: Random Param
      name: message
      type: string 
    - default: "https://github.com/jduimovich/rhtap-catalog.git"
      name: catalog-url
    - default: "main"
      name: catalog-revision
  tasks:
    - name: git-clone
      params:
        - name: url
          value:  $(params.git-url)
        - name: revision
          value: main
      taskRef: 
        resolver: git 
        params:
        - name: url
          value: $(params.catalog-url)
        - name: revision
          value: $(params.catalog-revision)
        - name: pathInRepo
          value: task/git-clone/0.1/git-clone.yaml 
      workspaces:
        - name: output
          workspace: workspace
    - name: print-message
      params:
        - name: message
          value:  "hi mom" 
      taskRef: 
        resolver: git
        params:
        - name: url
          value: $(params.catalog-url)
        - name: revision
          value: $(params.catalog-revision)
        - name: pathInRepo
          value: task/print-message/0.1/print-message.yaml
      workspaces:
        - name: output
          workspace: workspace
